### ISSUE TITLE
Вызов функции NazaCanDecoderLib_Decode в прерывании

### ISSUE THREAD

**Issue by Amomum** [DmitryRusSPb/CAN_protocol_stm32f103_SPL#6]
Это очень большая и развесистая функция, там много математики с плавающей точкой, работает она достаточно долго. Вызывать ее в прерывании - не очень хорошо. Прерывание должно работать как можно меньшее время, потому что оно *прерывает* работу всего остального кода (который может быть критичным по времени выполнения).

Если я правильно понимаю, NAZA сам ничего не говорит в CAN, а только отвечает на хартбиты. В таком случае проще внутри `Heartbeat `проверять флаг, что сообщение принято, а если принято - вызывать `NazaCanDecoderLib_Decode`, а прерывание вообще не использовать. 
Потому что не требуется быстрая реакция на прием сообщения.

**Comment by neuromozg** [comment]
> Если я правильно понимаю, NAZA сам ничего не говорит в CAN

Говорит регулярно, Heartbeat пакет который надо периодически закидывать, возможно даже достаточно один раз, что бы NAZA выдавала все данные, без Heartbeat будет в сильно усеченном виде, но NAZA сыплет данные сама, без запросов.

**Comment by Amomum** [comment]
@neuromozg а насколько регулярно? Т.е. с каким периодом?

**Comment by neuromozg** [comment]
Мы проверяли на коптере, вроде достаточно один раз отправить для инициализации передачи полного потока по CAN от NAZA. В оригинальном софте кидается раз в 1 сек.

**Comment by Amomum** [comment]
@neuromozg плохо спросил. Я хотел спросить "насколько регулярно NAZA сыплет данными сама?"

**Comment by neuromozg** [comment]
Пакеты летят достаточно быстро, но блоками
### время прихода блоков пакетов
**16 delta   ID  data ...                  < cansniffer can0 # l=20 h=100 t=500 >
0.199996  90      55 AA 55 AA 02 10 78 00 U.U...x.
0.200055  108    66 CC 66 CC             f.f.
0.999988  1FE   32 00 00 00 66 CC 66 CC 2...f.f.
0.999986  7F8   66 CC 66 CC             f.f.**
###  и как летят сами пакеты
 **(1524223404.671402)  can0  108   [8]  55 AA 55 AA 09 10 B8 00
 (1524223404.671514)  can0  108   [8]  44 4A 49 01 18 42 18 42
 (1524223404.671634)  can0  108   [8]  18 42 18 42 00 00 00 00
 (1524223404.671776)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.671889)  can0  108   [8]  17 FC E9 03 17 FC 00 00
 (1524223404.672006)  can0  108   [8]  EB 01 17 FC 17 FC E9 03
 (1524223404.672137)  can0  108   [8]  E9 03 E9 03 00 00 00 00
 (1524223404.672259)  can0  108   [8]  38 04 88 05 88 03 30 02
 (1524223404.672381)  can0  108   [8]  00 00 00 00 00 00 F1 7F
 (1524223404.672503)  can0  090   [8]  55 AA 55 AA 01 10 0E 00
 (1524223404.672627)  can0  090   [8]  03 00 00 00 31 00 00 00
 (1524223404.672748)  can0  090   [8]  16 00 00 00 16 6E 66 CC
 (1524223404.672815)  can0  090   [2]  66 CC
 (1524223404.672941)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.673066)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.673201)  can0  108   [8]  00 00 00 00 81 9E 00 00
 (1524223404.673318)  can0  108   [8]  EF 04 F3 C2 9C 00 18 43
 (1524223404.673433)  can0  108   [8]  49 60 0D C4 04 00 00 00
 (1524223404.673570)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.673686)  can0  108   [8]  00 00 48 C3 4F 2C 60 13
 (1524223404.673809)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.673944)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.674075)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.674197)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.674318)  can0  090   [8]  55 AA 55 AA 01 10 0E 00
 (1524223404.674441)  can0  090   [8]  03 00 00 00 2E 00 00 00
 (1524223404.674561)  can0  090   [8]  13 00 00 00 17 6E 66 CC
 (1524223404.674637)  can0  090   [2]  66 CC
 (1524223404.674757)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.674883)  can0  108   [8]  00 00 00 00 00 00 00 00
 (1524223404.675006)  can0  108   [8]  DA CC 35 3B 9B 13 1D C1**

**Comment by Amomum** [comment]
@neuromozg т.е. где-то 5-10 пакетов в миллисекунду? 
Это не слишком часто, на мой взгляд; обработку пакета в прерывании делать - перебор.

Если бы было чаще, в прерывании лучше перекладывать пакет в свою самодельную очередь, а потом обрабатывать спокойно.
